-- =============================================================================
-- AlatBerat - Skema Inti (ported dari Laravel 12 / SQLite)
-- Jalankan di Supabase SQL Editor, atau: supabase db push
-- =============================================================================

create extension if not exists "pgcrypto";

-- Status ketersediaan alat berat
create type public.equipment_status as enum ('available', 'rented', 'maintenance');

-- =============================================================================
-- TABEL
-- =============================================================================

create table public.admin_users (
    id uuid primary key references auth.users (id) on delete cascade,
    email text not null unique,
    name text not null,
    is_admin boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

comment on table public.admin_users is 'Profil admin yang terhubung dengan Supabase Auth';

create table public.categories (
    id bigint generated by default as identity primary key,
    name text not null,
    slug text not null unique,
    description text,
    icon text,
    image text,
    is_active boolean not null default true,
    sort_order integer not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table public.equipment (
    id bigint generated by default as identity primary key,
    category_id bigint not null references public.categories (id) on delete cascade,
    name text not null,
    slug text not null unique,
    brand text,
    model text,
    year integer,
    capacity text,
    description text,
    specifications jsonb,
    price numeric(15, 2),
    price_unit text,
    image text,
    images jsonb,
    status public.equipment_status not null default 'available',
    is_featured boolean not null default false,
    total_units integer not null default 1,
    available_units integer not null default 1,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint equipment_available_units_check check (available_units >= 0 and available_units <= total_units)
);

create table public.equipment_images (
    id bigint generated by default as identity primary key,
    equipment_id bigint not null references public.equipment (id) on delete cascade,
    image_path text not null,
    is_primary boolean not null default false,
    sort_order integer not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table public.services (
    id bigint generated by default as identity primary key,
    title text not null,
    slug text not null unique,
    description text,
    body text,
    icon text,
    image text,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table public.service_areas (
    id bigint generated by default as identity primary key,
    name text not null,
    slug text not null unique,
    description text,
    image text,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table public.projects (
    id bigint generated by default as identity primary key,
    title text not null,
    slug text not null unique,
    description text,
    body text,
    client text,
    location text,
    category text,
    equipment_used text,
    start_date date,
    end_date date,
    image text,
    images jsonb,
    is_featured boolean not null default false,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table public.project_images (
    id bigint generated by default as identity primary key,
    project_id bigint not null references public.projects (id) on delete cascade,
    image_path text not null,
    is_primary boolean not null default false,
    sort_order integer not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table public.blog_posts (
    id bigint generated by default as identity primary key,
    title text not null,
    slug text not null unique,
    excerpt text,
    body text,
    image text,
    author text,
    tags jsonb,
    is_published boolean not null default false,
    published_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table public.testimonials (
    id bigint generated by default as identity primary key,
    client_name text not null,
    client_position text,
    company text,
    photo text,
    content text not null,
    rating integer not null default 5,
    is_active boolean not null default true,
    is_featured boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint testimonials_rating_check check (rating between 1 and 5)
);

create table public.contacts (
    id bigint generated by default as identity primary key,
    name text not null,
    email text not null,
    phone text,
    company text,
    subject text,
    message text not null,
    is_read boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table public.faqs (
    id bigint generated by default as identity primary key,
    question text not null,
    answer text not null,
    category text,
    sort_order integer not null default 0,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

-- =============================================================================
-- INDEX
-- =============================================================================

create index equipment_category_id_idx on public.equipment (category_id);
create index equipment_status_idx on public.equipment (status);
create index equipment_is_featured_idx on public.equipment (is_featured) where is_featured;
create index equipment_images_equipment_id_idx on public.equipment_images (equipment_id);
create index projects_is_active_idx on public.projects (is_active);
create index projects_is_featured_idx on public.projects (is_featured) where is_featured;
create index project_images_project_id_idx on public.project_images (project_id);
create index blog_posts_is_published_idx on public.blog_posts (is_published, published_at desc);
create index testimonials_is_active_idx on public.testimonials (is_active);
create index contacts_is_read_idx on public.contacts (is_read);
create index faqs_sort_order_idx on public.faqs (sort_order);
create index categories_sort_order_idx on public.categories (sort_order);

-- =============================================================================
-- TRIGGER: updated_at otomatis
-- =============================================================================

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

do $$
declare
    t text;
begin
    foreach t in array array[
        'admin_users', 'categories', 'equipment', 'equipment_images', 'services',
        'service_areas', 'projects', 'project_images', 'blog_posts', 'testimonials',
        'contacts', 'faqs'
    ]
    loop
        execute format(
            'create trigger %I_set_updated_at before update on public.%I for each row execute function public.set_updated_at()',
            t, t
        );
    end loop;
end;
$$;

-- =============================================================================
-- HELPER: cek apakah user saat ini adalah admin
-- SECURITY DEFINER supaya tidak recursive RLS di admin_users
-- =============================================================================

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select coalesce(
        (select is_admin from public.admin_users where id = auth.uid()),
        false
    );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to anon, authenticated;

-- =============================================================================
-- ROW LEVEL SECURITY
-- Strategi:
--   - Konten publik  : SELECT untuk anon (hanya yang aktif/terbit)
--   - Konten privat  : SELECT hanya admin
--   - Tulis data      : admin saja, kecuali `contacts` (INSERT publik)
-- =============================================================================

alter table public.admin_users      enable row level security;
alter table public.categories       enable row level security;
alter table public.equipment        enable row level security;
alter table public.equipment_images enable row level security;
alter table public.services         enable row level security;
alter table public.service_areas    enable row level security;
alter table public.projects         enable row level security;
alter table public.project_images   enable row level security;
alter table public.blog_posts       enable row level security;
alter table public.testimonials     enable row level security;
alter table public.contacts         enable row level security;
alter table public.faqs             enable row level security;

-- admin_users: hanya admin yang boleh baca, tidak ada akses tulis via client
create policy "admin_users_select_admin" on public.admin_users
    for select to authenticated using (public.is_admin());

-- categories
create policy "categories_select_public" on public.categories
    for select to anon, authenticated using (is_active or public.is_admin());
create policy "categories_admin_all" on public.categories
    for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- equipment (katalog publik)
create policy "equipment_select_public" on public.equipment
    for select to anon, authenticated using (true);
create policy "equipment_admin_all" on public.equipment
    for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- equipment_images
create policy "equipment_images_select_public" on public.equipment_images
    for select to anon, authenticated using (true);
create policy "equipment_images_admin_all" on public.equipment_images
    for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- services
create policy "services_select_public" on public.services
    for select to anon, authenticated using (is_active or public.is_admin());
create policy "services_admin_all" on public.services
    for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- service_areas
create policy "service_areas_select_public" on public.service_areas
    for select to anon, authenticated using (is_active or public.is_admin());
create policy "service_areas_admin_all" on public.service_areas
    for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- projects
create policy "projects_select_public" on public.projects
    for select to anon, authenticated using (is_active or public.is_admin());
create policy "projects_admin_all" on public.projects
    for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- project_images
create policy "project_images_select_public" on public.project_images
    for select to anon, authenticated using (true);
create policy "project_images_admin_all" on public.project_images
    for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- blog_posts (hanya yang published & ada published_at)
create policy "blog_posts_select_public" on public.blog_posts
    for select to anon, authenticated using (
        (is_published and published_at is not null) or public.is_admin()
    );
create policy "blog_posts_admin_all" on public.blog_posts
    for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- testimonials
create policy "testimonials_select_public" on public.testimonials
    for select to anon, authenticated using (is_active or public.is_admin());
create policy "testimonials_admin_all" on public.testimonials
    for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- faqs
create policy "faqs_select_public" on public.faqs
    for select to anon, authenticated using (is_active or public.is_admin());
create policy "faqs_admin_all" on public.faqs
    for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- contacts: siapa pun boleh kirim pesan, hanya admin boleh baca/hapus
create policy "contacts_insert_public" on public.contacts
    for insert to anon, authenticated with check (true);
create policy "contacts_select_admin" on public.contacts
    for select to authenticated using (public.is_admin());
create policy "contacts_update_admin" on public.contacts
    for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "contacts_delete_admin" on public.contacts
    for delete to authenticated using (public.is_admin());
